version: '3.8'

name: YUP

services:
  app:
    container_name: bun-server
    image: verma2904/yup
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT:-3000}:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - yup_network
    restart: unless-stopped

networks:
  yup_network:
    driver: bridge

    # To build and start the containers:
    # docker-compose up --build

    # To start the containers without rebuilding:
    # docker-compose up

    # To stop the containers:
    # docker-compose down

    # To view running containers:
    # docker-compose ps

    # To view logs:
    # docker-compose logs

    # To run a command in the app container:
    # docker-compose exec app <command>
